#ifndef GENERAL_DEFINE_H
#define GENERAL_DEFINE_H

#define STATE_TASK_PRIORITY 2
#define DECISION_TASK_PRIORITY 1
#define ESTIMATE_TASK_PRIORITY 3
#define CONTROL_TASK_PRIORITY 4
#define RECEIVE_TASK_PRIORITY 3
#define SEND_TASK_PRIORITY 1
#define DEBUG_TASK_PRIORITY 1

#define STATE_TASK_PERIOD_MS 10U
#define DECISION_TASK_PERIOD_MS 10U
#define ESTIMATE_TASK_PERIOD_MS 1U
#define CONTROL_TASK_PERIOD_MS 5U
#define RECEIVE_TASK_PERIOD_MS 1U
#define SEND_TASK_PERIOD_MS 100U
#define DEBUG_TASK_PERIOD_MS 100U

#define IMU_GYRO_CALIBRATION_TIME_MS 20000U
//#define IMU_GYRO_CALIBRATION_ENABLE  1U
#define IMU_ACCEL_CALIBRATION_TIME_MS 20000U
#define ATTITUDE_ACCEL_LPF_ALPHA      0.95f
#define ATTITUDE_EKF_CHI_SQUARE_LIMIT 7.815f
#define ATTITUDE_EKF_CORRECTION_LIMIT 0.01f
#define ATTITUDE_MADGWICK_BETA        0.2f
#define ATTITUDE_MAX_SAMPLE_GAP_MS    20U
#define ATTITUDE_MIN_ACCEL_NORM_G     0.3f

#define STATE_TASK_STACK_SIZE 512
#define DECISION_TASK_STACK_SIZE 512  
#define ESTIMATE_TASK_STACK_SIZE 1024
#define CONTROL_TASK_STACK_SIZE 1024
#define RECEIVE_TASK_STACK_SIZE 1024
#define SEND_TASK_STACK_SIZE 1024
#define DEBUG_TASK_STACK_SIZE 1024

#define STATE_TASK_NAME "state_task"
#define DECISION_TASK_NAME "decision_task"
#define ESTIMATE_TASK_NAME "estimate_task"
#define CONTROL_TASK_NAME "control_task"
#define RECEIVE_TASK_NAME "receive_task"
#define SEND_TASK_NAME "send_task"
#define DEBUG_TASK_NAME "debug_task"

/* QTMR counts A rising edges only. Confirm 1024 is counts per encoder-shaft revolution in this mode. */
#define WHEEL_ENCODER_COUNTS_PER_ENCODER_REV 1024.0f
#define WHEEL_GEAR_TEETH                       68.0f
#define ENCODER_GEAR_TEETH                     30.0f
#define WHEEL_ENCODER_COUNTS_PER_REV           (WHEEL_ENCODER_COUNTS_PER_ENCODER_REV * \
                                               WHEEL_GEAR_TEETH / ENCODER_GEAR_TEETH)
#define WHEEL_DIAMETER_M                       0.064f
#define WHEEL_RADIUS_M                         (WHEEL_DIAMETER_M * 0.5f)
#define WHEEL_TRACK_M                          0.200f
#ifndef WHEEL_LEFT_COUNT_SIGN
#define WHEEL_LEFT_COUNT_SIGN        1
#endif
#ifndef WHEEL_RIGHT_COUNT_SIGN
#define WHEEL_RIGHT_COUNT_SIGN       -1
#endif
#define WHEEL_LEFT_PWM_FORWARD_LEVEL 0U
#define WHEEL_RIGHT_PWM_FORWARD_LEVEL 0U
#define MOTOR_PWM_FREQUENCY_HZ       17000U
#define MOTOR_TEST_TARGET_SPEED_MPS 1.0f
#define MOTOR_TEST_MAX_PWM_DUTY     5000U
#define MOTOR_LEFT_PWM_CHANNEL       PWM2_MODULE0_CHA_C6
#define MOTOR_LEFT_DIRECTION_PIN     C7
#define MOTOR_RIGHT_PWM_CHANNEL      PWM2_MODULE1_CHA_C8
#define MOTOR_RIGHT_DIRECTION_PIN    C9
#define ENCODER_LEFT_INDEX           QTIMER1_ENCODER1
#define ENCODER_LEFT_CHANNEL_1       QTIMER1_ENCODER1_CH1_C0
#define ENCODER_LEFT_CHANNEL_2       QTIMER1_ENCODER1_CH2_C1
#define ENCODER_RIGHT_INDEX          QTIMER1_ENCODER2
#define ENCODER_RIGHT_CHANNEL_1      QTIMER1_ENCODER2_CH1_C2
#define ENCODER_RIGHT_CHANNEL_2      QTIMER1_ENCODER2_CH2_C24
#define WHEEL_SPEED_PWM_POLARITY     1.0f
#define BALANCE_ANGLE_PWM_POLARITY   -1.0f
#define BALANCE_SPEED_TO_TILT_SIGN   1.0f

/* The wheel-speed test is independent of the balance cascade. */
#define WHEEL_SPEED_LOOP_PERIOD_MS   10U
#define WHEEL_SPEED_PWM_LIMIT        ((float)MOTOR_TEST_MAX_PWM_DUTY)
#define BALANCE_ANGLE_PERIOD_MS      5U
#define BALANCE_SPEED_PERIOD_MS      20U
#define BALANCE_UPRIGHT_PITCH_DEG    -90.0f
#define BALANCE_ANGLE_TARGET_PITCH_DEG -92.0f
#define BALANCE_SUPPORT_TARGET_PITCH_DEG -97.0f
#define BALANCE_ANGLE_PWM_LIMIT      3000.0f
#define ATTITUDE_ROLL_SIGN           -1.0f
#define BALANCE_TARGET_TILT_MAX_DEG  10.0f
#define BALANCE_SPEED_TARGET_MAX_MPS 1.0f
#define WHEEL_SPEED_KP               5000.0f
#define WHEEL_SPEED_KI               0.0f
#define WHEEL_SPEED_KD               100.0f
#define BALANCE_ANGLE_KP             600.0f
#define BALANCE_ANGLE_KI             0.0f
#define BALANCE_ANGLE_KD             30.0f
#define BALANCE_SPEED_KP             14.0f
#define BALANCE_SPEED_KI             3.0f
#define BALANCE_SPEED_KD             0.0f
#define CONTROL_PID_D_FILTER_ALPHA   0.6f

#define VEHICLE_BUTTON_DEBOUNCE_MS   30U
#define VEHICLE_BUTTON_CALIBRATE_PIN C12
#define VEHICLE_BUTTON_NAV_PIN       C13
#define VEHICLE_BUTTON_ARM_PIN       C14
#define VEHICLE_BUTTON_PROTECT_PIN   C15
#define VEHICLE_MODE_SWITCH_1_PIN    C26
#define VEHICLE_MODE_SWITCH_2_PIN    C27
#define VEHICLE_SWITCH_ON_LEVEL      0U
#define IMU_CALIBRATION_GYRO_MAX_DPS 3.0f
#define IMU_CALIBRATION_ACC_MIN_G    0.9f
#define IMU_CALIBRATION_ACC_MAX_G    1.1f
#define IMU_CALIBRATION_MIN_SAMPLES  100U
#define IMU_CALIBRATION_GYRO_NOISE_FLOOR_DPS2 0.000001f
#define IMU_CALIBRATION_ACC_NOISE_FLOOR_NORM2 0.000001f
#define VEHICLE_ATTITUDE_TIMEOUT_MS  30U
#define VEHICLE_STATE_TIMEOUT_MS     30U
#define VEHICLE_CONTROL_TIMEOUT_MS   30U
#define VEHICLE_ARM_PITCH_MAX_DEG    10.0f
#define VEHICLE_SUPPORT_ARM_PITCH_MAX_DEG 4.0f
#define VEHICLE_SUPPORT_AUTO_MIN_PITCH_DEG -100.0f
#define VEHICLE_SUPPORT_AUTO_MAX_PITCH_DEG -96.0f
#define VEHICLE_SUPPORT_AUTO_ENTER_MS 500U
#define VEHICLE_SUPPORT_EXIT_PITCH_DEG -96.0f
#define VEHICLE_SUPPORT_EXIT_MS 100U
#define VEHICLE_BALANCE_ENTRY_KICK_SPEED_MPS 0.15f
#define VEHICLE_BALANCE_ENTRY_KICK_MS         100U
#define VEHICLE_FALL_PITCH_MAX_DEG   45.0f
#define VEHICLE_SERIAL_TIMEOUT_MS    500U

/* Downlink command: A5 5A command data[4] xor(command,data). */
#define SERIAL_FRAME_SYNC_0          0xA5U
#define SERIAL_FRAME_SYNC_1          0x5AU
#define SERIAL_FRAME_LENGTH          8U
#define SERIAL_COMMAND_HEARTBEAT     0x00U
#define SERIAL_COMMAND_STATE         0x01U
#define SERIAL_COMMAND_SPEED         0x02U
#define SERIAL_COMMAND_YAW           0x03U
#define SERIAL_COMMAND_MOTION        0x04U
#define SERIAL_COMMAND_PID_BASE      0x50U
#define SERIAL_COMMAND_PID_LAST      0x58U
#define SERIAL_PID_CONTROLLER_WHEEL  0U
#define SERIAL_PID_CONTROLLER_ANGLE  1U
#define SERIAL_PID_CONTROLLER_SPEED  2U
#define SERIAL_PID_GAIN_KP            0U
#define SERIAL_PID_GAIN_KI            1U
#define SERIAL_PID_GAIN_KD            2U
#define SERIAL_PID_MAX_VALUE          10000.0f
#define SERIAL_STATE_PROTECT         0x00U
#define SERIAL_STATE_BALANCE         0x01U
#define SERIAL_STATE_NAVIGATION      0x02U
#define SERIAL_STATE_SUPPORT         0x03U
#define SERIAL_SPEED_SCALE_MPS       0.001f
#define SERIAL_YAW_SCALE_DEG         0.01f
#define SERIAL_TELEMETRY_SYNC_0      0x5AU
#define SERIAL_TELEMETRY_SYNC_1      0xA5U
#define SERIAL_TELEMETRY_VERSION     0x01U
#define SERIAL_TELEMETRY_TYPE        0x80U
#define SERIAL_TELEMETRY_LENGTH      52U
#define SERIAL_TELEMETRY_CRC_POLY    0x1021U
#define SERIAL_TELEMETRY_CRC_INIT    0xFFFFU
#define SERIAL_VALID_STATE           0x01U
#define SERIAL_VALID_ATTITUDE        0x02U
#define SERIAL_VALID_IMU             0x04U
#define SERIAL_VALID_MOTION          0x08U
#define SERIAL_VALID_CONTROL         0x10U
#define SERIAL_ANGLE_UNITS_PER_DEG   100.0f
#define SERIAL_RATE_UNITS_PER_DPS    100.0f
#define SERIAL_ACCEL_UNITS_PER_G     1000.0f
#define SERIAL_SPEED_UNITS_PER_MPS   1000.0f
#define SERIAL_PWM_LIMIT             10000
#define WHEEL_TWO_PI_RAD             6.283185307179586f
#define VEHICLE_UART_INDEX           UART_8
#define VEHICLE_UART_BAUD            115200U
#define VEHICLE_UART_RX_BUFFER_SIZE  128U
#define VEHICLE_UART_TX_PIN          UART8_TX_D16
#define VEHICLE_UART_RX_PIN          UART8_RX_D17

#endif 
